[package]
name = "telegram_bot"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"
lto = true
strip = true
opt-level = "s" # Optimize for size.

[dependencies]
structopt = "0.3"
teloxide = "0.12.2"
tokio = "1.33.0"
